language_code = {
    "Afrikaans"  	            :"af",
    "Albanian"  	            :"sq",
    "Amharic"   	            :"am",
    "Arabic"    	            :"ar",
    "Armenian"   	            :"hy",
    "Azeerbaijani" 	            :"az",
    "Basque" 	                :"eu",
    "Belarusian" 	            :"be",
    "Bengali"  	                :"bn",
    "Bosnian" 	                :"bs",
    "Bulgarian"                 :"bg",
    "Catalan" 	                :"ca",
    "Cebuano" 	                :"ceb",
    "Chinese (Simplified)"      :"zh-CN",
    "Chinese (Traditional)" 	:"zh-TW",
    "Corsican" 	                :"co",
    "Croatian"	                :"hr",
    "Czech" 	                :"cs",
    "Danish" 	                :"da",
    "Dutch" 	                :"nl",
    "English" 	                :"en",
    "Esperanto" 	            :"eo",
    "Estonian" 	                :"et",
    "Finnish"	                :"fi",
    "French" 	                :"fr",
    "Frisian" 	                :"fy",
    "Galician" 	                :"gl",
    "Georgian" 	                :"ka",
    "German" 	                :"de",
    "Greek" 	                :"el",
    "Gujarati" 	                :"gu",
    "Haitian Creole" 	        :"ht",
    "Hausa" 	                :"ha",
    "Hawaiian" 	                :"haw",
    "Hebrew" 	                :"iw",
    "Hindi" 	                :"hi",
    "Hmong" 	                :"hmn",
    "Hungarian" 	            :"hu",
    "Icelandic" 	            :"is",
    "Igbo" 	                    :"ig",
    "Indonesian" 	            :"id",
    "Irish" 	                :"ga",
    "Italian" 	                :"it",
    "Japanese" 	                :"ja",
    "Javanese" 	                :"jw",
    "Kannada" 	                :"kn",
    "Kazakh" 	                :"kk",
    "Khmer" 	                :"km",
    "Korean" 	                :"ko",
    "Kurdish" 	                :"ku",
    "Kyrgyz" 	                :"ky",
    "Lao" 	                    :"lo",
    "Latin" 	                :"la",
    "Latvian" 	                :"lv",
    "Lithuanian" 	            :"lt",
    "Luxembourgish" 	        :"lb",
    "Macedonian" 	            :"mk",
    "Malagasy" 	                :"mg",
    "Malay" 	                :"ms",
    "Malayalam" 	            :"ml",
    "Maori"	                    :"mi",
    "Marathi" 	                :"mr",
    "Mongolian" 	            :"mn",
    "Myanmar (Burmese)" 	    :"my",
    "Nepali" 	                :"ne",
    "Norwegian" 	            :"no",
    "Nyanja (Chichewa)" 	    :"ny",
    "Pashto" 	                :"ps",
    "Persian" 	                :"fa",
    "Polish"	                :"pl",
    "Portuguese" 	            :"pt",
    "Punjabi" 	                :"ma",
    "Romanian" 	                :"ro",
    "Russian" 	                :"ru",
    "Samoan" 	                :"sm",
    "Scots Gaelic" 	            :"gd",
    "Serbian" 	                :"sr",
    "Sesotho" 	                :"st",
    "Shona" 	                :"sn",
    "Sindhi" 	                :"sd",
    "Sinhala (Sinhalese)" 	    :"si",
    "Slovak" 	                :"sk",
    "Slovenian" 	            :"sl",
    "Somali" 	                :"so",
    "Spanish" 	                :"es",
    "Sundanese" 	            :"su",
    "Swahili" 	                :"sw",
    "Swedish" 	                :"sv",
    "Tagalog (Filipino)" 	    :"tl",
    "Tajik" 	                :"tg",
    "Tamil" 	                :"ta",
    "Telugu" 	                :"te",
    "Thai" 	                    :"th",
    "Turkish" 	                :"tr",
    "Ukrainian" 	            :"uk",
    "Urdu" 	                    :"ur",
    "Uzbek" 	                :"uz",
    "Vietnamese" 	            :"vi",
    "Welsh" 	                :"cy",
    "Xhosa" 	                :"xh",
    "Yiddish" 	                :"yi",
    "Yoruba"	                :"yo",
    "Zulu"                      :"zu"
}
YandexSupportLanguage = [
"Afrikaans",
"Albanian",
"Amharic",
"Arabic",
"Armenian",
"Azerbaijani",
"Bashkir",
"Basque",
"Belarusian",
"Bengali",
"Bosnian",
"Bulgarian",
"Burmese",
"Catalan",
"Cebuano",
"Croatian",
"Czech",
"Danish",
"Dutch",
"English",
"Esperanto",
"Estonian",
"Finnish",
"French",
"Galician",
"Georgian",
"German",
"Greek",
"Gujarati",
"Haitian",
"Hebrew",
"Hindi",
"Hungarian",
"Icelandic",
"Indonesian",
"Irish",
"Italian",
"Javanese",
"Kannada",
"Kazakh",
"Khmer",
"Korean",
"Kyrgyz",
"Lao",
"Latin",
"Latvian",
"Lithuanian",
"Luxembourgish",
"Macedonian",
"Malagasy",
"Malay",
"Malayalam",
"Maori",
"Marathi",
"Mongolian",
"Nepali",
"Norwegian",
"Persian",
"Polish",
"Portuguese",
"Punjabi",
"Romanian",
"Russian",
"Serbian",
"Sinhalese",
"Slovak",
"Slovenian",
"Spanish",
"Sundanese",
"Swahili",
"Swedish",
"Tagalog",
"Tajik",
"Tamil",
"Telugu",
"Thai",
"Turkish",
"Ukrainian",
"Urdu",
"Uzbek",
"Vietnamese",
"Welsh",
"Xhosa",
"Yiddish"
]
speechLanguageSupport = [
'af',
'bg',
'bs',
'ca',
'cs',
'cy',
'da',
'de',
'el',
'en',
'eo',
'es',
'et',
'fa',
'fi',
'fr',
'ga',
'hi',
'hr',
'hu',
'hy',
'id',
'is',
'it',
'ka',
'kn',
'ku',
'la',
'lt',
'lv',
'mk',
'ml',
'ms',
'ne',
'nl',
'no',
'pl',
'pt',
'ro',
'ru',
'sk',
'sq',
'sr',
'sv',
'sw',
'ta',
'tr',
'vi',
'zh-TW'
]
